### PR TITLE
Clear dialog reference when dismissed (fixes #305).

### LINKED ISSUE #305: RuntimeException: Unable to start service
```
java.lang.RuntimeException: Unable to start service com.nutomic.syncthingandroid.syncthing.SyncthingService@88e0e52 with Intent { cmp=com.nutomic.syncthingandroid/.syncthing.SyncthingService }: java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{36ee35f5 V.E..... R......D 0,0-1368,652} not attached to window manager
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
at android.app.ActivityThread.access$2100(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{36ee35f5 V.E..... R......D 0,0-1368,652} not attached to window manager
at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
at android.app.Dialog.dismissDialog(Dialog.java:341)
at android.app.Dialog.dismiss(Dialog.java:324)
at com.nutomic.syncthingandroid.activities.MainActivity.onApiChange(MainActivity.java:98)
at com.nutomic.syncthingandroid.syncthing.SyncthingService.onApiChange(SyncthingService.java:400)
at com.nutomic.syncthingandroid.syncthing.SyncthingService.updateState(SyncthingService.java:225)
at com.nutomic.syncthingandroid.syncthing.SyncthingService.onStartCommand(SyncthingService.java:149)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
... 9 more
```

### PR DESCRIPTION
**Pull request by Zillode**

### CODE REVIEW

File: src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java [hunk 1]
```diff
@@ -207,7 +208,9 @@ public void onDestroy() {
         super.onDestroy();
         if (mLoadingDialog != null) {
             mLoadingDialog.dismiss();
+            mLoadingDialog = null;
         }
+        mDisabledDialog = null;
```
Comment (Nutomic) [inline src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java]: This one's useless.

**Comment by Zillode** [comment]
Bumped
