### PR TITLE
Refactor SyncthingService (lifecycle), DeviceStateHolder, RestApi, multiple fixes

### LINKED ISSUE #1019: No connection over OpenVPN unless "Run only on wifi" unchecked
### Starting point:
- server configured with local discovery only
- android client configured with the following
  - local discovery only
  - "Run only on wifi"

### What happens:
- android client is on a public wifi; syncthing client is not connected; everything here is exactly as expected
- android client successfully establishes connection using OpenVPN; at this point I would expect successful connection but instead "Syncthing Options" and "Backup" becomes greyed out and syncthing client is not connected to the sync server; this is unexpected since android client is still on wifi

### Workaround:
- on android client: uncheck "Run only on wifi" under "Run Conditions"; "Syncthing Options" and "Backup" become available and syncthing client establishes connection

### Version Information
Syncthing Version: v0.14.43, Linux (64 bit)
App Version: v0.14.43
Android Version: Android 8.1.0
OpenVPN Connect 1.1.27 (build 96)

### LINKED ISSUE #1104: Duplicate syncthing binary starts by SyncthingService
The log shows "Another syncthing instance is already running" and then next line "Restarting syncthing" every time I open the app or on first app start after installation.

To further diagnose the problem, I captured some logs with additional "log points" in place and indeed got multiple startup attempts of the SyncthingRunnable caused by SyncthingService.

Logs attached.
App Version: 0.10.10 (and newer commits)
Syncthing Version: v0.14.47
Android Version: Android 7.1.2 /  LineAgeOS

grafik
grafik
grafik
grafik
grafik

I've made a PR to fix this. Uploading it shortly...

### LINKED ISSUE #1115: SyncthingService endless restarts binary on run condition change
Reproducer on current master's code base
Install syncthing app while wifi is on.
Go to settings > run conditions > 
always run in background = yes
run on wifi = yes

Disable phone's wifi. Works.
Enable phone's wifi.  Endless syncthing binary restarts due to DeviceStateHolder issuing multiple change events to syncthing service even if the final decision to run or terminate the binary did not change.

Getting into it, I think the SyncthingService#updateState function containing an previously present in the code "HACK" is to blame. I'm currently investigating, if this fix helps:
`// HACK: Make sure there is no syncthing binary left running from an improper
            // shutdown (eg Play Store update).
            if (mCurrentState == State.INIT) {
                shutdown(State.INIT, () -> {
                    Log.i(TAG, "Starting syncthing according to current state and preferences");
                    new StartupTask().executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);
                });
            }`

Log:
`06-02 14:06:52.609 I/DeviceStateHolder(9650): Listening for network state changes
06-02 14:06:52.619 I/DeviceStateHolder(9650): Listening to battery state changes
06-02 14:06:52.624 I/DeviceStateHolder(9650): Listening to power saving changes
06-02 14:06:52.652 I/DeviceStateHolder(9650): State updated, allowed network connection: true, charging: false, power saving: false
06-02 14:06:52.654 D/DeviceStateHolder(9650): All SSIDs allowed for syncing
06-02 14:06:52.655 I/DeviceStateHolder(9650): State updated, allowed network connection: true, charging: false, power saving: false
06-02 14:06:52.659 D/DeviceStateHolder(9650): All SSIDs allowed for syncing
06-02 14:06:52.659 I/DeviceStateHolder(9650): State updated, allowed network connection: true, charging: false, power saving: false
06-02 14:06:52.662 D/DeviceStateHolder(9650): All SSIDs allowed for syncing
06-02 14:06:52.669 I/DeviceStateHolder(9650): State updated, allowed network connection: true, charging: false, power saving: false
06-02 14:06:52.671 D/DeviceStateHolder(9650): All SSIDs allowed for syncing
06-02 14:06:52.777 I/SyncthingRunnableKill(9650): Killed Syncthing process 9714
06-02 14:06:52.792 I/DeviceStateHolder(9650): Listening for network state changes
06-02 14:06:52.801 I/DeviceStateHolder(9650): Stopped listening to battery state changes
06-02 14:06:52.803 I/DeviceStateHolder(9650): Listening to power saving changes
06-02 14:06:52.835 D/SyncthingRunnable(9650): killSyncthing: Found no more running instances of libsyncthing.so
06-02 14:06:52.845 I/DeviceStateHolder(9650): State updated, allowed network connection: true, charging: false, power saving: false
06-02 14:06:52.850 D/DeviceStateHolder(9650): All SSIDs allowed for syncing
06-02 14:06:52.850 I/SyncthingService(9650): Shutting down background service
06-02 14:06:52.850 D/EventProcessor(9650): Shutdown event processor.
06-02 14:06:52.859 I/SyncthingService(9650): Starting syncthing according to current state and preferences
06-02 14:06:52.860 I/DeviceStateHolder(9650): State updated, allowed network connection: true, charging: false, power saving: false
06-02 14:06:52.860 D/ConfigXml(9650): Trying to read '/data/user/0/com.nutomic.syncthingandroid.debug/files/config.xml'
06-02 14:06:52.865 I/ConfigXml(9650): Loaded Syncthing config file
06-02 14:06:52.866 I/ConfigXml(9650): Found existing config version 28
06-02 14:06:52.867 D/DeviceStateHolder(9650): All SSIDs allowed for syncing
06-02 14:06:52.867 I/SyncthingService(9650): Shutting down background service
06-02 14:06:52.867 D/EventProcessor(9650): Shutdown event processor.
06-02 14:06:52.870 D/NotificationService(952): stripForegroundServiceFlag: Could not find notification with pkg=com.nutomic.syncthingandroid.debug / id=4 / userId=0
06-02 14:06:52.878 I/SyncthingService(9650): Starting syncthing according to current state and preferences
06-02 14:06:52.883 D/ConfigXml(9650): Trying to read '/data/user/0/com.nutomic.syncthingandroid.debug/files/config.xml'
06-02 14:06:52.887 I/ConfigXml(9650): Loaded Syncthing config file
06-02 14:06:52.887 I/ConfigXml(9650): Found existing config version 28
06-02 14:06:52.890 V/LASTMESSAGEg(5835): Received last update Syncthing ist deaktiviert - 
06-02 14:06:52.898 I/ConfigXml(9650): Writing updated config file
06-02 14:06:52.906 I/ConfigXml(9650): Writing updated config file
06-02 14:06:52.916 V/LASTMESSAGEg(5835): Received last update Syncthing ist deaktiviert - `

Together with #1116 the following bad situation occurs, when DeviceStateHolder is used to monitor run conditions and a run condition (like the wifi condition) changes here:
image

### LINKED ISSUE #1120: DeviceStateHolder leaks Receivers not unregistered
Reproducer
Open Syncthing app
go to settings
enable always run syncthing on background
enable run on wifi
disable run on wifi
go back to home screen
press back button
from home screen press syncthing is running notification
go to settings
disable always run syncthing on background
go to MainActivity
exit syncthing app

image

    Report valid for: https://github.com/syncthing/syncthing-android/commit/165c136beae31514d701791c9f654b2568338f46
    App Version: 0.10.10+
    Syncthing Version: v0.14.47
    Android Version: Android 7.1.2

### LINKED ISSUE #1121: SettingsActivity calls out to uninitialized RestApi.getLocalDevice()
Reproducer
Open Syncthing app
go to settings
enable always run syncthing on background
stress test the UI options
* run when charging
* run on wifi

Do this fast, slow, fast, fast with two or three fingers and hit the buttons as much as you can. The app crashes "under your fingers".

image

With more logs:
image

    Report valid for: https://github.com/syncthing/syncthing-android/commit/165c136beae31514d701791c9f654b2568338f46
    App Version: 0.10.10+
    Syncthing Version: v0.14.47
    Android Version: Android 7.1.2

### LINKED ISSUE #1122: NPE in WebGuiActivity.onWebGuiAvailable()
Reproducer
Setup syncthing with a large database ( ~ 200 MByte ) with many folders so it takes more time to initialize
Open Syncthing app
go to settings
enable always run syncthing on background
enable run on wifi
enable run when charging
get back to MainActivity
open webGUI

stress test by changing the run conditions as quickly as possible
* wifi on/off
* lay phone on/off wireless charger)

SyncthingService will get the run condition change correctly and tries to catch up with them. But there are many problems in the lifecycle code and multiple calls to RestApi.onWebGuiAvailable(), transitions from State.Starting to State.Disabled without waiting for the binary to finish (and more ...)
onWebGuiAvailable(STATE) will be issued to the webGuiActivity causing a crash accessing the config in an "intermediate invalid object state".

image

    Report valid for: https://github.com/syncthing/syncthing-android/commit/165c136beae31514d701791c9f654b2568338f46
    App Version: 0.10.10+
    Syncthing Version: v0.14.47
    Android Version: Android 7.1.2

### LINKED ISSUE #1123: Multiple Web GUI has come online - invalid state transitioning
Reproducer
Open Syncthing app
go to settings
enable always run syncthing on background
put phone to wifi and put it on the charger
stress test the UI options
* run when charging
* run on wifi

Do this fast, slow, fast, fast with two or three fingers and hit the buttons as much as you can. The app crashes "under your fingers".

image

It's notable here that there are two problems hidden under the hood:
a) PollWebGuiAvailableTask has no "dismiss" or "abort" interface
Looking at the logs and reproducing it time over time I discovered that the service goes correctly down to State.DISABLED and tries to get up with State.INIT > State.STARTING > State.ACTIVE.
If run conditions are changing to rapidly we again have bad unsynchronized runtime behaviour. The service transitions from State.STARTING >State.DISABLED >  STATE.INIT > State.STARTING ....
a1) not waiting for the syncthing binary to finish its work on gracefull kill signal. This sometimes results in left-behind concurrently running syncthing instances corrupting the database if syncthing takes some seconds to load up. 
a2) not discarding the PollWebGuiAvailableTask from a "queue" so we get more and more of them and as syncthing binary is fully initialized, every PollWebGuiAvailableTask  triggers the callback in RestApi reading the config. So three or more simultaneous requests and result listeners try to modify one mConfig entity - calling out the reached state.ACTIVE with onApiChange() to all parts of the wrapper and whoooom... crashed. Transitioning from state.ACTIVE to state.ACTIVE is not considered in the existing code and never should be as it would add more complexity.

Also affects
* Multiple EventProcessor run concurrently with the same timeIdx=0 ... 7 ... 15 ... and getting weird results > probably the root cause for ticket https://github.com/syncthing/syncthing-android/issues/679 (multiple instances of SyncthingService, mRestApi, EventProcessor might have been created)

    Report valid for: https://github.com/syncthing/syncthing-android/commit/165c136beae31514d701791c9f654b2568338f46
    App Version: 0.10.10+
    Syncthing Version: v0.14.47
    Android Version: Android 7.1.2

### LINKED ISSUE #1124: FirstStartActivity calls startService() - wrong lifecycle
Reproducer
Start the syncthing app
You're in MainActivity
open Settings screen
press home button
click the notification on top OR click the app's icon in the app drawer from android's launcher

Problem
service gets multiple onStartCommand's which are unneccessary and prone to subsequent errors

Log
image

image

Improvement
MainActivity is not disposed while syncthing app is not exited or running in the background and
a1) is reused if user clicks the notification on the status bar.
a2) is reused we are already running and the user comes "again" from the app launcher.

    Report valid for: https://github.com/syncthing/syncthing-android/commit/165c136beae31514d701791c9f654b2568338f46
    App Version: 0.10.10+
    Syncthing Version: v0.14.47
    Android Version: Android 7.1.2

### LINKED ISSUE #1125: Syncthing is disabled dialog not showing after settingschange
Reproducer
Start the syncthing app
You're in MainActivity
open Settings screen
change run conditions to something that should cause syncthing to get disabled
go back to MainActivity

Problem
The syncthing disabled dialog is not shown. Instead I see my folders up2date and status info on the drawer causing me to incorrectly think syncthing is running. Looking at the notification, it states "sycnthing is disabled". If syncthing is force-closed and relaunched from the android launcher's app drawer, the dialog is correctly shown. It is also correctly shown, if a run condition changes to "shouldRun" and back to "shouldNotRun" while sitting before the wrong "green up2date running UI with statuses".

Root cause
StateDialogActivity does only react to onApiChange() signals issued by the syncthing service upon starting / terminating syncthing after getting notified by DeviceStateHolder about changed run conditions.

Fix
If MainActivity is resumed, the SyncthingService.State has to be read and by StateDialogActivity .onResume.
PR #1119 , commits:
https://github.com/syncthing/syncthing-android/pull/1119/commits/b9584ddcc49251a4cb46318f5c49d4215b6028c9
https://github.com/syncthing/syncthing-android/pull/1119/commits/18a59862e65256f988a5bb16facf2164211cbde5

    Report valid for: https://github.com/syncthing/syncthing-android/commit/165c136beae31514d701791c9f654b2568338f46
    App Version: 0.10.10+
    Syncthing Version: v0.14.47
    Android Version: Android 7.1.2

### LINKED ISSUE #1126: Settings screen / run conditions WifiSSIDSelector UI glitch
Reproducer
Open settings screen
go to run conditions screen
Initial state: "always run in background" = disabled
enable "always run in background"
(only charging checkbox turns from greyed out to available)
(only wifi checkbox turns from greyed out to available)
(wifi ssid selection checkbox stays greyed out)
enable "only wifi checkbox"
("wifi ssid selection checkbox" turns from greyed out to available)
disable "always run in background"
(only charging checkbox gets greyed out and unchecked)
(only wifi checkbox gets greyed out and unchecked)
(== BUG == "wifi ssid selection checkbox" stays available NOT greyed out -> it should get greyed out!)

Fix in PR #1119 commit https://github.com/Catfriend1/syncthing-android/commit/dd0f84e740e5d7716a5f28fe8abe9da0b47ccd63

### Version Information
    App Version: 0.10.10+ (and ealier versions)
    Syncthing Version: v0.14.47
    Android Version: Android 7.1.2

### PR DESCRIPTION
**Pull request by ghost**
... SyncthingRunnable, settings UI and listeners.

Fixed issue list from what's already on the tracker:
(fixes #1019) (maybe related to #975)

Fixed issues I discovered testing every UI stress test I could think of and regular syncthing options/wrapper behaviour under various run conditions or foreground run - I created issues for those:
(fixes #1120) - DeviceStateHolder leaks Receivers not unregistered
(fixes #1121) - SettingsActivity calls out to uninitialized RestApi.getLocalDevice() 
(fixes #1122) - NPE in WebGuiActivity.onWebGuiAvailable()
(fixes #1123) - Multiple Web GUI has come online - invalid state transitioning
(fixes #1124) - FirstStartActivity calls startService() - wrong lifecycle
(fixes #1125) - Syncthing is disabled dialog not showing after settingschange
(fixes #1104) - follow-up PR, see post in issue
(fixes #1115) - corresponds to #1104 
(fixes #1126) - Settings screen / run conditions WifiSSIDSelector UI glitch

This PR is a base for further improvement regarding the following issues:
https://github.com/syncthing/syncthing-android/issues/937
https://github.com/syncthing/syncthing-android/issues/914
https://github.com/syncthing/syncthing-android/issues/612
https://github.com/syncthing/syncthing-android/issues/588
https://github.com/syncthing/syncthing-android/issues/523 - as we can make more use of Events API (EventProcessor) in the future after this "spider web" of interacting accross threads/classes and recreating activities more than once got solved.
https://github.com/syncthing/syncthing-android/issues/549 - run conditions can now be further refined

Hi together,
after a 24 hours bug fixing marathon I refactored the syncthing wrapper's code to solve multiple issues related to simultaneously started threads, event processing on listeners, concurrend access to objects that should be locked on multithread access, airplane mode, wifi ssid's settings UI, receiver leaks due to the lack of "isReceiverRegistered" in Android plus registering a receiver more than once or under pref circumstances not registering any receiver which causes syncthing to completely fail startup in background service mode.
I recall something around 20 bugs discovered and fixed by now. I've simplified the code accross classes to a minimum extend of using listeners and callbacks only where necessary. Plus, log output has been added where its crucial to understand the lifecycle of SyncthingService, SyncthingRunnable and asynchronous broadcasts/callbacks from DeviceStateHolder and RestApi. I'll post details and logs on some issues that exist in the current master tomorrow as I'm really tired now (please forgive me). We can then review that whole thing.
I've already tested this to work as much as I could, also stress testing the settings UI and wildly changing real conditions to see if any crash results and for now - it looks good and crash free. The current master has a lot of problems if for example the user stresses the run conditions UI and/or quits syncthing. Also Activity lifecycles weren't correct - now MainActivity is kept on clicking the notification instead of being relaunched against the SingleTask policy (see manifest) All in all, Syncthing wrapper's UI feels much faster and I couldn't get it to crash. Another problem from the master code was, "Syncthing is disabled" wasn't properly maintained or shown if run conditions and/or settings according to that changed or MainActivity was onBackPressed or paused.
I would love your feedback on testing the TeamCity APK.
Promise to open the single issues ASAP so we have a good write up whats fixed by this PR.
Kind regards

### CODE REVIEW

**Comment by Catfriend1** [comment]
(draft - still editing)
Fixed issue list from what's already on the tracker:
https://github.com/syncthing/syncthing-android/issues/1019
https://github.com/syncthing/syncthing-android/issues/975
https://github.com/syncthing/syncthing-android/issues/781 - SyncthingService lifecycle now ensures, that states aren't skipped or sent to onApiChange() multiple times.

This PR is a base for further improvement regarding the following issues:
https://github.com/syncthing/syncthing-android/issues/937
https://github.com/syncthing/syncthing-android/issues/914
https://github.com/syncthing/syncthing-android/issues/612
https://github.com/syncthing/syncthing-android/issues/588
https://github.com/syncthing/syncthing-android/issues/523 - as we can make more use of Events API (EventProcessor) in the future after this "spider web" of interacting accross threads/classes and recreating activities more than once got solved.
https://github.com/syncthing/syncthing-android/issues/549 - run conditions can now be further refined

File: app/src/main/java/com/nutomic/syncthingandroid/service/ReceiverManager.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+        }
+    }
+
+    public static void unregisterAllReceivers(Context context) {
+        if (context == null) {
+            Log.e(TAG, "unregisterReceiver: context is null");
+            return;
+        }
+        Iterator<BroadcastReceiver> iter = mReceivers.iterator();
+        while (iter.hasNext()) {
```
Comment (Catfriend1) [inline app/src/main/java/com/nutomic/syncthingandroid/service/ReceiverManager.java]: Note - this has to be an iterator and not a foreach(). If using foreach, elements mustn't be removed which we need to do. See foreach() crash that got solved by using the iterator.
image

File: app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java [hunk 2]
```diff
@@ -140,26 +147,38 @@ public RestApi(Context context, URL url, String apiKey, OnApiAvailableListener a
     /**
      * Gets local device ID, syncthing version and config, then calls all OnApiAvailableListeners.
      */
-    @Override
-    public void onWebGuiAvailable() {
-        mAvailableCount.set(0);
+    public void readConfigFromRestApi() {
```
Comment (Catfriend1) [inline app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java]: Relates to https://github.com/syncthing/syncthing-android/issues/1121

File: app/src/main/java/com/nutomic/syncthingandroid/activities/WebGuiActivity.java [hunk 3]
```diff
@@ -140,20 +140,31 @@ public void onCreate(Bundle savedInstanceState) {
...
+        getService().registeronServiceStateChangeListener(this);
     }
 
     @Override
-    public void onWebGuiAvailable() {
-        if (mWebView.getUrl() == null) {
-            mWebView.stopLoading();
-            setWebViewProxy(mWebView.getContext().getApplicationContext(), "", 0, "localhost|0.0.0.0|127.*|[::1]");
-            mWebView.loadUrl(getService().getWebGuiUrl().toString());
+    public void onServiceStateChange(SyncthingService.State newState) {
```
Comment (Catfriend1) [inline app/src/main/java/com/nutomic/syncthingandroid/activities/WebGuiActivity.java]: Fix for https://github.com/syncthing/syncthing-android/issues/1122 - Solution:
Only expose onWebGuiAvailable to RestApi (where the only important place from my point of view is where it's really needed) and implement onServiceStateChange() (before PR it's called onApiChange)

**Comment by Catfriend1** [comment]
@AudriusButkevicius Ready for review. I can confirm this build is working perfectly on my Android 7.1.2 phone model lg-h815. I tested the shit out of it as much as I could. Would appreciate more people testing the debug apk and giving feedback. All in all, syncthingService now sticks to clear lifecycle DISABLED > INIT > STARTING > ACTIVE > DISABLED > ... (as the most used lifeycle). This is the main achievement making the code  as @Nutomic said beforehand "it could be in the need of a complete rewrite" more straightforward eliminating easy to discover bugs and settling sophisticated threadsafe operation correct.

**Comment by AudriusButkevicius** [comment]
Uhh, this is unreviewable.
Can we break this down into 5 or however many we need small PRs that address one issue at a time?
There is so much stuff moving here that it's impossible to grasp, and the best I could do is just merge with my eyes closed, and hope for the best.

**Comment by AudriusButkevicius** [comment]
`#1121 - SettingsActivity calls out to uninitialized RestApi.getLocalDevice()`
I know Google Play console is full on NPEs related to the RestApi being uninitialized, so we should have a closer look everywhere it's used.

**Comment by Catfriend1** [comment]
About those restApi NPE's you are right. They are caused because of the broken lifecycle the syncthingservice goes through especially on run condition change. The most fundamental fault I discovered was signalling State.Active where other modules expect restapi to be fully ready called out a) too early by bad implementation of the callback or b) staggering concurrently running pollers calling back multiple times causing multiple concurrent accessing of restapi init stuff and variables.

**Comment by Catfriend1** [comment]
I know this is hard to review as I wanted to do the code refactoring initially focusing on two issues but everytime trying to incrementally verify it works correctly a new fundamental Problem with the code came up. To get it quality assured I put a log more verbose log in the "hot" places and played over my whole stress test and real test case procedure again and again last night after making improvements until no more issues were found aroung the wrappers core classes. Do you think merging as a separate beta tag and release is possible? Wouls you mind in assisting me by trying out a test build? I've also had my difficulties with all the logs from yesterday creating those issues and referring to what part was mostly relevant in fixing them. Split up would be very time consuming and - having experienced how long the rewrite of certain parts and dependencies took due to a lot of thread, listener and callback code - took, most likely from my point of view not give us an stable master build.

**Comment by AudriusButkevicius** [comment]
You should really try to work in an organized way.
I know it's easy to get side-tracked and go fix all the bugs you find, on the left and right, but remember that someone will have to understand the change and approve it. If you see something easy to fix, `git add -u; git commit -m WIP; git checkout origin/master; git branch fix-this-other-thing` and fix that small thing and file a separate PR.

When contributing to Go, I was asked to open a separate PR for renaming a variable, so that renames and functionality lives in separate PRs.
This is just to set the gauge of the atmosphere when 1k blob of changes comes in, with convoluted ideas, and no idea which change fixes what issue or why it's there to start with.

I am pretty sure no open source project would appreciate this type of pull request, even if it fixes all bugs under the sun, especially as there is no tests proving that it actually works.

I don't use syncthing, so yeah, I can start the app and see that it launches, but this is as far as it goes me helping test things. 

Sure, we can make a gradual rollout of the next version, and **hope** that people catch the issues before they figure out that we shat in their bed and come for us with pitchforks.

**Comment by AudriusButkevicius** [comment]
I mean, I made some meaningless comments, as I have no idea why some of the changes are happening in the first place.

I guess once you deal with my "it's named wrong, I think you need a lock" nonsense, we'll let it brew for a while in hopes that someone else comes in and reviews this.

If not, we'll merge it, and hope for the best.
If shit does hit the fan, I'll let you do the cleanup I guess.

**Comment by Catfriend1** [comment]
Thanks for taking time to comment. I'm looking into every comment tomorrow and answer as good as I can. Also found some parts I can improve by your feedback before we discuss merge. I'm sleeping a night over it if I can split it up, maybe on module base. Youre right that this was an uncommon way to get from one thing to another rewriting more and more... Hope you'll forgive me finally in the favour of a fixed basement the app stands on. I definitely don't intend to work like this untargeted in the future. If issues arise from the changes I'll accept the work to solve them. Getting back with answers shortly...

**Comment by Catfriend1** [comment]
@AudriusButkevicius  I took care of the review aspects. Any more suggestions to improve this PR? If not, please leave me a message so I will do a time expensive testing of the whole app with a) a new setup and b) an existing setup including different settings/settings and run condition changes/stress testing, large and small databases to verify everything works correctly before merge. If something breaks, I'll assist in fixing them, sure.

**Comment by Catfriend1** [comment]
Update: I roughly tested the current debug build on latest commit after the big test yesterday and it works without a single android runtime exception. Done this rough test earlier than planned to decide if I can point a ticket OP to the newest debug build. Lifecycles are okay, receivers too. What I did:
Installed debug apk fresh
Stress tested ui with run condition changes and changes to prefs
Imported my sync config
Restarted syncthing app from the drawer menu
Opened web gui activity
Clicked the status bar notification after switching away.
Went to settings and set conditions so syncthing wont run, got back to main activity, hit exit, clicked the notification, changed prefs back for running syncthing
Opened the web ui
Exited the app.
Made some nice looking photos of the logs, logs are okay, will upload them later.

P.s. Should I put all fixed issues (as they are many) in the PR's title?

**Comment by AudriusButkevicius** [comment]
Put them in the body, I think git parses that too.

**Comment by Catfriend1** [comment]
@AudriusButkevicius Done, I also put my log screenshots up for proving this to be verified and working on my Android 7.1.2 phone.

File: app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java [hunk 4]
```diff
@@ -124,11 +142,6 @@ public RestApi(Context context, URL url, String apiKey, OnApiAvailableListener a
...
     private final AtomicInteger mAvailableCount = new AtomicInteger(0);
 
-    /**
-     * Number of asynchronous calls performed in {@link #onWebGuiAvailable()}.
-     */
-    private static final int TOTAL_STARTUP_CALLS = 3;
-
     public interface OnApiAvailableListener {
         void onApiAvailable();
     }
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java]: Is this still used?

File: app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java [hunk 5]
```diff
@@ -311,7 +330,13 @@ private void removeFolderInternal(String id) {
...
 
     public Device getLocalDevice() {
-        for (Device d : getDevices(true)) {
+        List<Device> devices = getDevices(true);
+        if (devices.isEmpty()) {
+            Log.e(TAG, "getLocalDevice: devices is empty");
+            throw new RuntimeException();
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java]: That's not a very useful exception...

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java [hunk 6]
```diff
@@ -263,48 +263,43 @@ private boolean useWakeLock() {
...
+            } catch (IOException e) {
+                Log.w(TAG_NICE, "Failed to close shell stream", e);
+            }
+            if (nice != null) {
+                nice.destroy();
+            }
+            if (ret != 0) {
+                Log.e(TAG_NICE, "Failed to set ionice " + Integer.toString(ret));
+            }
+        }
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java]: Why was this in a thread before?

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 7]
```diff
@@ -59,18 +59,8 @@
...
-    public interface OnWebGuiAvailableListener {
-        void onWebGuiAvailable();
-    }
-
-    private final HashSet<OnWebGuiAvailableListener> mOnWebGuiAvailableListeners =
-            new HashSet<>();
-
-    public interface OnApiChangeListener {
-        void onApiChange(State currentState);
+    public interface onServiceStateChangeListener {
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: Interface should start with a capital letter. I am surprised lint does not bitch about it.

File: app/src/main/java/com/nutomic/syncthingandroid/activities/StateDialogActivity.java [hunk 8]
```diff
@@ -69,24 +79,25 @@ private void onApiChange(SyncthingService.State currentState) {
                 dismissLoadingDialog();
                 break;
             case DISABLED:
-                dismissLoadingDialog();
-                if (!isFinishing()) {
+                if (!mIsPaused) {
                     showDisabledDialog();
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/activities/StateDialogActivity.java]: Will this not show a dialog on top?

File: app/src/main/java/com/nutomic/syncthingandroid/service/DeviceStateHolder.java [hunk 9]
```diff
@@ -70,19 +71,26 @@ public static boolean alwaysRunInBackground(Context context) {
...
-    private @Nullable BatteryReceiver mBatteryReceiver = null;
-    private @Nullable BroadcastReceiver mPowerSaveModeChangedReceiver = null;
+    private @Nullable DeviceStateChangedReceiver mDeviceStateChangedReceiver = null;
+    private ReceiverManager mReceiverManager;
 
-    private boolean mIsAllowedNetworkConnection;
+    // Those receivers are managed by {@link mReceiverManager}.
+    private NetworkReceiver mNetworkReceiver;
+    private BatteryReceiver mBatteryReceiver;
+    private PowerSaveModeChangedReceiver mPowerSaveModeChangedReceiver = null;
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/DeviceStateHolder.java]: Why is this nulled, and others are not?

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 10]
```diff
@@ -234,34 +274,86 @@ protected Void doInBackground(Void... voids) {
...
+            if (mApi == null) {
+                mApi = new RestApi(SyncthingService.this, mConfig.getWebGuiUrl(), mConfig.getApiKey(),
+                                    SyncthingService.this::onApiAvailable, () -> onServiceStateChange(mCurrentState));
+                Log.i(TAG, "Web GUI will be available at " + mConfig.getWebGuiUrl());
+            }
 
-            pollWebGui();
+            // Start the syncthing binary.
+            if (mSyncthingRunnable != null || mSyncthingRunnableThread != null) {
+                Log.e(TAG, "StartupTask/onPostExecute: Syncthing binary lifecycle violated");
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: This errors does no good. Should we crash or just return here?

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 11]
```diff
@@ -234,34 +274,86 @@ protected Void doInBackground(Void... voids) {
...
+        if (mDestroyScheduled) {
+            mDestroyScheduled = false;
+            stopSelf();
+            return;
+        }
+
+        if (mEventProcessor == null) {
+            mEventProcessor = new EventProcessor(SyncthingService.this, mApi);
+        }
+        mEventProcessor.start();
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: Do you really want to double start it if it already exists?

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 12]
```diff
@@ -350,60 +451,37 @@ public void registerOnWebGuiAvailableListener(OnWebGuiAvailableListener listener
...
-                    return;
-                }
-            }
-            Log.i(TAG, "Web GUI has come online at " + mConfig.getWebGuiUrl());
-            onApiChange(State.STARTING);
-            Stream.of(mOnWebGuiAvailableListeners).forEach(OnWebGuiAvailableListener::onWebGuiAvailable);
-            mOnWebGuiAvailableListeners.clear();
-        });
+    public void unregisterOnServiceStateChangeListener(onServiceStateChangeListener listener) {
+        mOnServiceStateChangeListeners .remove(listener);
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: space before dot.

**Comment by AudriusButkevicius** [comment]
So the screenshots of logs have literally no value to me, just makes the page harder to load.

I made some new comments, and a lot of my questions are still not answered.

File: app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java (hunk 4 above)
Comment (AudriusButkevicius) [reply app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java]: The interface, is that used?

File: app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java (hunk 5 above)
Comment (AudriusButkevicius) [reply app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java]: That's still not a useful exception, regardless that the error message is good.
Error messages will not be sent to google play.

**Comment by AudriusButkevicius** [comment]
I ask a question and you start removing things.
I ask to put a message in the exception, you expand the message in log line, that is never ever visible to anyone.

Are you reading the review comments or are you still working on this and I should come back later?

**Comment by Catfriend1** [comment]
@AudriusButkevicius Yeah the logs make more sense if one debugs the app with multiple test plans manually, collects logs before and after this PR and compares them to see where improvements act a new way.
Sorry that I've overseen 2 or 3 comments unintentionally, I didn't notice they were hidden behind "Load diff" looking through your review. I answered them plus the new ones and made improvement commits :). Thanks for reviewing this big a second time.
Are we ready now for me doing the "big test" of the latest debug apk again to verify this PR working?

**Comment by AudriusButkevicius** [comment]
There are still plenty of things that were not addressed/answered.

**Comment by AudriusButkevicius** [comment]
Also removing the ionice and stuff? Why are we removing it? If there is a good reason, why does this have to happen in this PR?

File: app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java (hunk 4 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java]: | The interface, is that used? |
Did this overlap with my last post? > Answer is yes, see SynctingService#onApiAvailable

File: app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java (hunk 5 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java]: Ok got the point. So we need a good error message thrown "to google play". I'm going to improve this shorty ...

Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java]: I put the log message to be thrown as RuntimeException. commit https://github.com/syncthing/syncthing-android/pull/1119/commits/9bdc1a7ebf72bd563bf2e7b2340479db9ead5d97

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java (hunk 6 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java]: Removing it was just a proposal as I think the person getting this in meant to address an older syncthing version before 0.14.47. I'm reverting this as I agree with you we can remove it later. To sum up my answer to the question: No need for a new thread. Can stay as it is and won't do harm.
Revert with commit https://github.com/syncthing/syncthing-android/pull/1119/commits/bd08037e07e81c37d54cca5a4e6e30ba3d62e880

**Comment by Catfriend1** [comment]
@AudriusButkevicius 
I've now answered and addressed everything that was on the code review (link https://github.com/syncthing/syncthing-android/pull/1119/files/872e7721ea989c2750ab99555f249fde3a2a25bb ) did I miss something?
At the time of you writing I'd have to apologize that I did not F5 this page working on the review tab and got this afterwards.  I was indeed still going to the review on doing improvements that came up to my mind reading your questions. Now I'm done. The RuntimeException was a misunderstanding as I just focused on the logs, it's improved now. Thanks for hitting my head hard to the wall until I finally got the point :).
I reverted the niceSyncthing removal so we have this part in again, agreed to remove it later as this is really big now.

**Comment by AudriusButkevicius** [comment]
There is still plenty of stuff unanswered, just go to the files tab, and check.

**Comment by Catfriend1** [comment]
Sorry, I logged out, clicked the link and recognized you couldn't see my comments?! I was somehow in pending review mode and hit this button
image
total github beginner :(

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java (hunk 6 above)
Comment (AudriusButkevicius) [reply app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java]: `"nices out itself" on since binary version 0.14.47+`, not ionice, which is what this is doing.

File: app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java [hunk 13]
```diff
@@ -136,11 +136,16 @@ public void onSaveInstanceState(Bundle outState) {
      * Invokes status callbacks.
      */
     private void updateGui() {
-        if (mActivity.getApi() == null || getActivity() == null || getActivity().isFinishing())
+        if (getActivity() == null || getActivity().isFinishing()) {
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java]: There is a race between checking if getActivity is null and it actually being null on the secons call, causing a NPE. Probably store the getActivitiy value in a variable.

File: app/src/main/java/com/nutomic/syncthingandroid/activities/DeviceActivity.java [hunk 14]
```diff
@@ -214,7 +214,7 @@ private void restoreDialogStates(Bundle savedInstanceState) {
     public void onDestroy() {
         super.onDestroy();
         if (getService() != null) {
-            getService().unregisterOnApiChangeListener(this::onApiChange);
+            getService().unregisterOnServiceStateChangeListener(this::onServiceStateChange);
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/activities/DeviceActivity.java]: What if getServics returns a null on the second invocation?

File: app/src/main/java/com/nutomic/syncthingandroid/activities/FolderActivity.java [hunk 15]
```diff
@@ -235,7 +235,7 @@ private Bundle getVersioningBundle() {
     public void onDestroy() {
         super.onDestroy();
         if (getService() != null) {
-            getService().unregisterOnApiChangeListener(this);
+            getService().unregisterOnServiceStateChangeListener(this);
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/activities/FolderActivity.java]: Ditto about second call

File: app/src/main/java/com/nutomic/syncthingandroid/activities/FolderPickerActivity.java [hunk 16]
```diff
@@ -156,13 +156,13 @@ private void populateRoots() {
...
-        getService().registerOnApiChangeListener(this);
+        getService().registerOnServiceStateChangeListener(this);
     }
 
     @Override
     protected void onDestroy() {
         super.onDestroy();
-        getService().unregisterOnApiChangeListener(this);
+        getService().unregisterOnServiceStateChangeListener(this);
     }
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/activities/FolderPickerActivity.java]: Can this be null?

File: app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java (hunk 13 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java]: That's better, done with commit https://github.com/Catfriend1/syncthing-android/commit/13a180dc49c27bf80a3d1565f55dd55e93d96a0c

File: app/src/main/java/com/nutomic/syncthingandroid/activities/FolderActivity.java (hunk 15 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/activities/FolderActivity.java]: improved with commit https://github.com/Catfriend1/syncthing-android/commit/66ed4bdda02820267bd1dc33b31561a8eac1b54e
see above.

File: app/src/main/java/com/nutomic/syncthingandroid/activities/DeviceActivity.java (hunk 14 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/activities/DeviceActivity.java]: improved with commit https://github.com/Catfriend1/syncthing-android/commit/66ed4bdda02820267bd1dc33b31561a8eac1b54e
This is just a safety check already present on the old code. But yes, I agree storing the ref on a variable and use this is better so I did improve that. As we shutdown the syncthing service first an d then finish MainActivity (holding this fragment) which calls onDestroy() getService couldn't get null while this code part is running at the moment (but in a future implementation maybe :) )

File: app/src/main/java/com/nutomic/syncthingandroid/activities/FolderPickerActivity.java (hunk 16 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/activities/FolderPickerActivity.java]: No can't be, same explanation as I posted in https://github.com/syncthing/syncthing-android/pull/1119#discussion_r193385835 (see DeviceActivity question).
We should anyway null check this to make future implementations more easy not to run into issues here. Done by commit https://github.com/Catfriend1/syncthing-android/commit/9393e6fdd8869c93a95ad16fb76bb1fcd7b3ba0b .

**Review by AudriusButkevicius — APPROVED** [review]

**Comment by AudriusButkevicius** [comment]
I guess I already made it quite clear previously, but, there is no way anything like this will ever get merged again.

**Comment by Catfriend1** [comment]
Right, okay. I'm also standing for this ugly pr to be a one time occurence to make the code clean.

**Comment by Catfriend1** [comment]
Note on testing: I got 2h 53m stable syncthing binary execution testing with Android 7.1.2 on lg-h815 with the RestartOnWakeup option set to disabled.
image

**Comment by capi** [comment]
Sorry, I will not have time to really review this huge PR (thanks for the gigantic work, @Catfriend1), and I read along in the mails with @AudriusButkevicius doing a great job at reviewing the changes while they came in.

I'll try to compile and install this branch sometime this weekend and just try if everything _in my usecase_ works, in order to contribute a little bit to testing.

I am with @AudriusButkevicius that PRs should be smaller. For this huge PR I am struggling a bit if we should merge it squashed or not? Normally I am pro-squashing on merge, but the individual steps at least show the intention of most changes. But having a huge block of 83 commits merged in, I'm just not sure.

**Comment by Catfriend1** [comment]
@capi : If you need the latest commit of this PR built, you can grab it here https://build.syncthing.net/repository/download/SyncthingAndroid_Build/22103:id/debug/app-debug.apk
I suggest squashing commits from beginning until (https://github.com/syncthing/syncthing-android/pull/1119/commits/6c00e7aad0b93dcd70daa9bed90c3aa0735a75f3 ) together into one commit. After this "WIP" commit, every commit addressed one issue at once not affecting the whole bunch of code that much then it was before.

**Comment by capi** [comment]
Thanks, but I need to compile myself, since my current version is self-compiled and installed and otherwise the signing keys won't match.

**Comment by Catfriend1** [comment]
@capi : I think you have your reasons for the self-compile :) let me know if you have some code ready we can check in perhaps for everyone to benefit or make the app's syncthing data backup & restore more mightful. (I recently thought about also backing up the index but for unexperienced users this could be risky)
