### PR TITLE
Fix leak in SyncthingService.StartupTask (fixes #1135)

### LINKED ISSUE #1135: Leak probability in SyncthingService.AsyncTask
image

image

see build warnings [lint-results.zip](https://github.com/syncthing/syncthing-android/files/2097072/lint-results.zip)

    App Version: 0.10.11 (and earlier)
    Syncthing Version: v0.14.48
    Android Version: Android 7.1.2

### PR DESCRIPTION
**Pull request by ghost**
Purpose
Fix issue https://github.com/syncthing/syncthing-android/issues/1135 . Will also get rid of the lint warnings about the wrong implementation of the AsyncTask in SyncthingService.StartupTask .
This is no urgent problem, according to StackOverflow https://stackoverflow.com/questions/44309241/warning-this-asynctask-class-should-be-static-or-leaks-might-occur/46166223#46166223 its not leaking in most use cases.
See issue for more details and discussion about the way chosen to solve this.
Related #1140 #1141 #1142 

Testing
Verified working correctly under Android 7.1.2 , lg-h815.

Merging aspects
This is the first out of four PR's to fix the "AsyncTask class should be implemented as private static" problems from the current lint report. So please wait until I got all four PR ready, then I'll test through everything and we can merge them.

### CODE REVIEW

**Comment by Catfriend1** [comment]
Verified working correctly under Android 7.1.2 , lg-h815.

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 1]
```diff
@@ -250,80 +251,113 @@ private void onUpdatedShouldRunDecision(boolean newShouldRunDecision) {
...
-            if (mApi == null) {
-                mApi = new RestApi(SyncthingService.this, mConfig.getWebGuiUrl(), mConfig.getApiKey(),
-                                    SyncthingService.this::onApiAvailable, () -> onServiceStateChange(mCurrentState));
-                Log.i(TAG, "Web GUI will be available at " + mConfig.getWebGuiUrl());
-            }
-
-            // Start the syncthing binary.
-            if (mSyncthingRunnable != null || mSyncthingRunnableThread != null) {
-                Log.e(TAG, "StartupTask/onPostExecute: Syncthing binary lifecycle violated");
+    private void LaunchStartupTask () {
```
Comment (Nutomic) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: Should be `launchStartupTask()` (lowercase L).

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 2]
```diff
@@ -250,80 +251,113 @@ private void onUpdatedShouldRunDecision(boolean newShouldRunDecision) {
...
+                 syncthingService.StartupTask_onPostExecute();
+             }
+             return;
+         }
+     }
+
+     /**
+      * Callback on {@link StartupTask#onPostExecute}.
+      */
+     private void StartupTask_onPostExecute() {
```
Comment (Nutomic) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: Should be something like `onStartupTaskCompleteListener()`, because method names in Java are supposed to be camel case without underscores.

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 3]
```diff
@@ -250,80 +251,113 @@ private void onUpdatedShouldRunDecision(boolean newShouldRunDecision) {
...
 
     /**
-     * Called when {@link PollWebGuiAvailableTask} confirmed the REST API is available.
-     * We can assume mApi being available under normal conditions.
+     * Sets up the initial configuration, and updates the config when coming from an old
+     * version.
+     */
+     private static class StartupTask extends AsyncTask<Void, Void, Void> {
+
+         private WeakReference<SyncthingService> refSyncthingService;
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: Noop blank line after the method signature?
I am pretty sure if you press Ctrl + Alt + L in Android studio, nitpicks like this get fixed automatically.

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 4]
```diff
@@ -250,80 +251,113 @@ private void onUpdatedShouldRunDecision(boolean newShouldRunDecision) {
...
+         }
+
+         @Override
+         protected void onPostExecute(Void aVoid) {
+             // Get a reference to the service if it is still there.
+             SyncthingService syncthingService = refSyncthingService.get();
+             if (syncthingService != null) {
+                 syncthingService.onStartupTaskCompleteListener();
+             }
+             return;
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: What's the point of this return?

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 5]
```diff
@@ -250,80 +251,113 @@ private void onUpdatedShouldRunDecision(boolean newShouldRunDecision) {
...
+
+         StartupTask(SyncthingService context) {
+             refSyncthingService = new WeakReference<>(context);
+         }
+
+         @Override
+         protected Void doInBackground(Void... voids) {
+             SyncthingService syncthingService = refSyncthingService.get();
+             if (syncthingService == null) {
+                 cancel(true);
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: Should we not return here?

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 6]
```diff
@@ -250,80 +251,113 @@ private void onUpdatedShouldRunDecision(boolean newShouldRunDecision) {
...
+             mPollWebGuiAvailableTask = new PollWebGuiAvailableTask(
+                     this,
+                     getWebGuiUrl(),
+                     mConfig.getApiKey(),
+                     result -> {
+                 Log.i(TAG, "Web GUI has come online at " + mConfig.getWebGuiUrl());
+                 if (mApi != null) {
+                     mApi.readConfigFromRestApi();
+                 }
+             });
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: The indentation here is strange, either do:
```
new Foo(bar, baz, nuff, squeek -> {
   blah
});
```
or

```
new Foo(
   bar, baz, nuf, squeek -> {
       faf();
   }
);
```

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java (hunk 3 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: removed blank line. Thanks for the hint.

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java (hunk 5 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: yes, fixed.

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java (hunk 4 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: no longer needed > removed

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java (hunk 6 above)
Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: Ok, agreed. Second suggestion looks better than my original indent :)

**Review by AudriusButkevicius — APPROVED** [review]

**Comment by Catfriend1** [comment]
Lgtm

File: app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java [hunk 7]
```diff
@@ -250,80 +251,110 @@ private void onUpdatedShouldRunDecision(boolean newShouldRunDecision) {
...
                         mApi.readConfigFromRestApi();
                     }
-                });
-            }
-        }
-    }
+                }
+             );
+         }
+         return;
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java]: Pointless return

**Comment by Catfriend1** [comment]
Ready for merge.

**Review by AudriusButkevicius — APPROVED** [review]
