### PR TITLE
Fix NPE in DrawerFragment if syncthing is terminated (fixes #1148)

### LINKED ISSUE #1148: NPE in DrawerFragment if syncthing is terminated
If syncthing was terminated while Drawer is expanded and run conditions change:
When the user then would hit "show qr code" a NPE occured before the PR. (see list in issue #1146)

Error Log
java.lang.NullPointerException: at com.nutomic.syncthingandroid.service.RestApi.getGui (RestApi.java:375) at com.nutomic.syncthingandroid.fragments.DrawerFragment.showQrCode (DrawerFragment.java:210) at com.nutomic.syncthingandroid.fragments.DrawerFragment.onClick (DrawerFragment.java:241)

### PR DESCRIPTION
**Pull request by ghost**
Purpose
Fix NPE if syncthing was terminated while Drawer is expanded and run conditions change. When the user then would hit "show qr code" a NPE occured before the PR. (see list in issue #1146, issue #1148)

Error Log
java.lang.NullPointerException: at com.nutomic.syncthingandroid.service.RestApi.getGui (RestApi.java:375) at com.nutomic.syncthingandroid.fragments.DrawerFragment.showQrCode (DrawerFragment.java:210) at com.nutomic.syncthingandroid.fragments.DrawerFragment.onClick (DrawerFragment.java:241)

Testing
Just a null check, don't think it needs testing. Please tell me if it does.

### CODE REVIEW

File: app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java [hunk 1]
```diff
@@ -206,10 +206,15 @@ private void onReceiveConnections(Connections connections) {
      */
 
     private void showQrCode() {
+        RestApi restApi = mActivity.getApi();
+        if (restApi == null) {
+            Toast.makeText(mActivity, R.string.syncthing_terminated, Toast.LENGTH_SHORT).show();
+            return;
+        }
+        String apiKey = restApi.getGui().apiKey;
+        String deviceId = restApi.getLocalDevice().deviceID;
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java]: Wouldn't these throw exceptions if syncthing was shutdown after checking rest api but before calling getLocalDevice etc?

Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java]: Maybe that can happen, but the shutdown then has to occur simultaneously from another thread which we currently don't have.

Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java]: Any suggestions how to improve this or can we merge it as a first-aid?

Comment (AudriusButkevicius) [reply app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java]: All of this startup, shutdown, stuff and element access should be behind a lock, there is a ton of NPE's happening because we just happen to access these global things without any locks at random times.

Comment (AudriusButkevicius) [reply app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java]: Perhaps wrap this whole thing in a try catch, and say an error has occoured if you get an exception.

File: app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java [hunk 2]
```diff
@@ -211,15 +214,19 @@ private void showQrCode() {
...
+            String deviceId = restApi.getLocalDevice().deviceID;
+            URL url = restApi.getUrl();
+            //The QRCode request takes one paramteer called "text", which is the text to be converted to a QRCode.
+            new ImageGetRequest(mActivity, url, ImageGetRequest.QR_CODE_GENERATOR, apiKey,
+                    ImmutableMap.of("text", deviceId),qrCodeBitmap -> {
+                mActivity.showQrCodeDialog(deviceId, qrCodeBitmap);
+                mActivity.closeDrawer();
+            }, error -> Toast.makeText(mActivity, R.string.could_not_access_deviceid, Toast.LENGTH_SHORT).show());
+        } catch (Exception e) {
+            Log.e(TAG, "showQrCode", e);
```
Comment (AudriusButkevicius) [inline app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java]: Do we need to show something to the user, or will it be obvious once the drawer is closed?

Comment (Catfriend1) [reply app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java]: I think in most cases a problem occurs here we'll hit the part that shows the toast to the user. That's enough for me.
> if (restApi == null) {
 -        String deviceId = mActivity.getApi().getLocalDevice().deviceID;		 +            Toast.makeText(mActivity, R.string.syncthing_terminated, Toast.LENGTH_SHORT).show();
 -        URL url = mActivity.getApi().getUrl();		 +            return;
 -        new ImageGetRequest(mActivity, url, ImageGetRequest.QR_CODE_GENERATOR, apiKey,		 +        }

**Review by AudriusButkevicius — APPROVED** [review]
