### PR TITLE
Ensure Syncthing is not running (fixes #92 and #96)

### LINKED ISSUE #92: Syncthing Binary Crashed  - error code 2
Hi,
I just updated syncthing to version 0.4.8 using Google Play (I suppose this is the version due to the comments... "disallow adding the same node multiple times" ...)
When running, this popup comes:

Syncthing Binary Crashed
The syncthing binary has exited with error code 2.
If this error persists, try reinstalling the app and restarting your device.

I've tried both but still happens...

any suggestions ?
(I am using android-2.3.7 - CyanogenMode-7.2.0-blade, on ZTE-Blade)

### PR DESCRIPTION
**Pull request by Zillode**
Ensure Syncthing is not running
- Fixes a bug: api.shutdown() is called asynchronously (line 278)
- Kills Syncthing processes on shutdown (e.g. when the /rest/shutdown call could not be applied because ST was too busy).

### CODE REVIEW

**Comment by Nutomic** [comment]
I would move the logging into the loop, or into `killProcessId()`, so it only logs actual kills. Do you think one second is enough time on slower devices?

Please add a docstring to `killProcessId()` and log exceptions. And a unit test would be very nice ;)

**Comment by Nutomic** [comment]
Oh and Github only understands `fixes #x, fixes #y` apparently.

File: src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java [hunk 1]
```diff
@@ -131,6 +133,82 @@ public void run() {
...
+                psOut.writeBytes("ps | grep libsyncthing.so\n");
+                psOut.writeBytes("exit\n");
+                psOut.flush();
+                ps.waitFor();
+                InputStreamReader isr = new InputStreamReader(ps.getInputStream());
+                BufferedReader br = new BufferedReader(isr);
+                String id;
+                while ((id = br.readLine()) != null) {
+                    killProcessId(id, i > 0);
+                }
```
Comment (Nutomic) [inline src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java]: You don't seem to check if the kill succeeds, so you run it 3 times in any case. Which gives us the same problem if someone stops and immediately starts the app.

File: src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java [hunk 2]
```diff
@@ -131,6 +133,82 @@ public void run() {
...
+        DataOutputStream killOut = null;
+        try {
+            kill = Runtime.getRuntime().exec("sh");
+            killOut = new DataOutputStream(kill.getOutputStream());
+            if (!force) {
+                killOut.writeBytes("kill " + id + "\n");
+                killOut.writeBytes("sleep 1\n");
+            } else {
+                killOut.writeBytes("sleep 3\n");
+                killOut.writeBytes("kill -9 " + id + "\n");
```
Comment (Nutomic) [inline src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java]: What's the logic with the sleep here? (different values and different command order) I think it should go into the end of the loop rather than here.

**Comment by Nutomic** [comment]
Oh and log shows `E/SyncthingNativeCode﹕ Syncthing binary crashed with error code 143`, is there any way we can avoid that? (without removing that logging entirely)

File: src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java (hunk 2 above)
Comment (Zillode) [inline src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java]: 1) perform a nice kill and wait one second
2) check which processes exist
3) if it still exists, wait 3 extra seconds and then kill it hard

File: src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java (hunk 1 above)
Comment (Zillode) [inline src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java]: This is done synchronously

File: src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java (hunk 2 above)
Comment (Nutomic) [inline src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java]: Yeah but I don't think we really need the SIGKILL, I've never had trouble to kill a command line program with CTRL-C. Like I said, this could be a problem if a new syncthing instance is started after the call, because it would then be killed.

Comment (Zillode) [inline src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java]: It won't because I changed the async ```PostTask().execute(mUrl, PostTask.URI_SHUTDOWN, mApiKey)``` to a blocking operation. I cannot see a path that would kill it when ST should be starting.
I could remove the sigkill, but then there is no guarantee it will be stopped.
